---
- hosts: crib
  vars:
    - ansible_user: root
    - ansible_password: loggedin
    - ansible_port: 22
  vars_files:
    - "{{ vaultdir }}/setboxes/pass.yml"
  roles:
    - role: convert_boot
      hosts: bios
    - role: initialize
