---
- hosts: crib
  vars:
    - ansible_user: root
    - ansible_password: loggedin
    - ansible_port: 22
  vars_files:
    - "{{ vaultdir }}/setboxes/cred.yml"
  roles:
    - role: convert_boot
      when: "'bios' in group_names"
    - role: initialize
