---
- hosts: all
  become: true
  vars_files:
    - "{{ vaultdir }}/setboxes/vault.yml"
  roles:
    # core
    - role: initialize
    - role: baseline
    - role: pacman
    - role: mkinitcpio
    - role: packages
    - role: udev
    # software
    - role: vim
    # mss-wares
    - role: mss_otg
    - role: mss_nfqws
    # networking
    - role: networking
    - role: wireguard
    - role: nftables
    # services
    - role: bind
    - role: docker
    - role: libvirt
      when: "'libvirt' in pkgs"
    - role: bulk_svc
    - role: cleanup
