---
- hosts: crib
  become: true
  vars_files:
    - "{{ vaultdir }}/setboxes/cred.yml"
    - "{{ vaultdir }}/setboxes/router.yml"
  roles:
    # core
    - role: initialize
    - role: baseline
    - role: pacman
    - role: mkinitcpio
    - role: packages
    - role: udev
    - role: modules
    # software
    - role: vim
    - role: x11
      when: "'desktops' in group_names"
    # mss-wares
    - role: mss_otg
    - role: mss_nfqws
    # networking
    - role: systemd_networkd
    - role: wireguard
    - role: router_netns
      when: "'routers' in group_names"
    - role: networkmanager
      when: "'desktops' in group_names"
    - role: pppd
      when: "'routers' in group_names and ppp_wan"
    # services
    - role: node_exporter
      when: "'routers' in group_names"
    - role: systemd_logind
    - role: nftables
    - role: bind
    - role: docker
      when: '"docker" in pkgs'
    - role: libvirt
      when: "'libvirt' in pkgs"
    - role: pulseaudio
      when: "'desktops' in group_names"
    - role: mpd
      when: "'desktops' in group_names"
    - role: ntpd
    - role: tor
      when: "'desktops' in group_names"
    - role: acpid
      when: "'acpid' in pkgs"
    - role: thinkfan
      when: "'thinkfan' in pkgs"
    - role: bulk_svc
    - role: cleanup
