---
- hosts: crib
  become: true
  vars_files:
    - "{{ vaultdir }}/setboxes/pass.yml"
    - "{{ vaultdir }}/setboxes/router.yml"
  roles:
    # core
    - role: initialize
    - role: baseline
    - role: pacman
    - role: mkinitcpio
    - role: packages
    - role: udev
    - role: modules
    # software
    - role: vim
    - role: x11
      hosts: desktops
    # mss-wares
    - role: mss_otg_utils
    - role: mss_otg_landfill
      hosts: desktops
    - role: mss_nfqws
    # networking
    - role: systemd_networkd
    - role: wireguard
    - role: router_netns
      hosts: routers
    - role: networkmanager
      hosts: desktops
    - role: pppd
      hosts: routers
      when: ppp_wan
    # services
    - role: systemd_logind
    - role: nftables
    - role: bind
    - role: docker
      when: '"docker" in pkgs'
    - role: libvirt
      when: "'libvirt' in pkgs"
    - role: pulseaudio
      hosts: desktops
    - role: mpd
      hosts: desktops
    - role: ntpd
    - role: tor
      hosts: desktops
    - role: acpid
      when: "'acpid' in pkgs"
    - role: thinkfan
      when: "'thinkfan' in pkgs"
    - role: bulk_svc
    - role: cleanup
