---
- name: install dnsmasq_netns unit file
  copy:
    src: dnsmasq_netns@.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
  register: dnsmasq_netns_unitfile_copy

- name: install wg-quick-lan_crib unit file
  template:
    src: wg-quick-lan_crib@.service.j2
    dest: /etc/systemd/system/wg-quick-lan_crib@.service
    owner: root
    group: root
    mode: '0644'
  register: wg_quick_lan_crib_unitfile_copy

- name: daemon reload
  systemd_service:
    daemon_reload: true
  when: >-
    (
      dnsmasq_netns_unitfile_copy.changed or
      wg_quick_lan_crib_unitfile_copy.changed
    )

- name: install guest vlan netns
  include_role:
    name: make_vlan_netns
  vars:
    netns_name: guest

- name: install crib vlan netns
  include_role:
    name: make_vlan_netns
  vars:
    netns_name: crib

- name: configure wireguard instances for lan_crib netns
  block:
    - name: enabled by default, if in a vm
      systemd_service:
        name: "wg-quick-lan_crib@{{ item }}"
        enabled: true
      with_items: "{{ mss_wireguard_ifaces }}"
      when: in_vm

    - name: triggers, when on baremetal
      systemd_service:
        name: "wg-quick-lan_crib@{{ item }}"
        state:
          "{{ \
            'restarted' if \
              wg_config_link.changed or \
              wg_quick_lan_crib_unitfile_copy.changed \
            else \
              'started' \
          }}"
        enabled: true
      with_items: "{{ mss_wireguard_ifaces }}"
      when: not in_vm
