---
- name: set up libvirt service
  block:
    - name: copy over libvirtdns service
      copy:
        src: libvirtdns.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: '0644'
      register: libvirtdns_copy

    - name: copy over libvirtd overrides
      copy:
        src: libvirtd.service.d
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: '0644'
      register: libvirtd_systemd_override

    - name: handle libvirt changes
      block:
        - name: daemon reload
          systemd_service:
            daemon_reload: true

        - name: stop all in order
          systemd_service:
            name: "{{ item }}"
            state: stopped
            enabled: true
          with_items:
            - libvirtd.service
            - virtlogd.service
            - libvirtd-admin.socket
            - libvirtd-ro.socket
            - libvirtd.socket
            - virtlockd.socket
            - virtlogd.socket
      when: >-
        (
          libvirtd_systemd_override.changed or
          libvirtdns_copy.changed
        )

- name: set libvirt state
  systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - libvirtd
    - virtlogd
  changed_when: false

- name: register config
  block:
    - name: define networks
      community.libvirt.virt_net:
        command: define
        name: "{{ item.name }}"
        xml: '{{ lookup("file", item.xml) }}'
      with_items:
        - { name: "virt", xml: "virtxml/net_virt.xml" }

    - name: define pools
      community.libvirt.virt_pool:
        command: define
        name: "{{ item.name }}"
        xml: '{{ lookup("file", item.xml) }}'
      with_items:
        - { name: "virt", xml: "virtxml/pool_virt.xml" }
        - { name: "iso", xml: "virtxml/pool_iso.xml" }

    - name: set status
      block:
        - name: activate networks
          community.libvirt.virt_net:
            state: active
            name: virt

        - name: autostart networks
          community.libvirt.virt_net:
            autostart: true
            name: virt

        - name: activate pools
          community.libvirt.virt_pool:
            state: active
            name: "{{ item }}"
          with_items:
            - virt
            - iso

        - name: autostart networks
          community.libvirt.virt_pool:
            autostart: true
            name: "{{ item }}"
          with_items:
            - virt
            - iso
      when: not in_vm
