---
- name: copy over the acpid handler script
  copy:
    src: handler.sh
    dest: /etc/acpi
    owner: root
    group: root
    mode: '0755'
  register: acpid_copy

- name: set acpid state
  systemd_service:
    name: acpid
    state: "{{ 'restarted' if acpid_copy.changed else 'started' }}"
    enabled: true
