---
- name: copy over the pacman config files
  copy:
    src: "{{ item }}"
    dest: /etc
    owner: root
    group: root
    mode: '0644'
  with_items:
    - pacman.conf
    - makepkg.conf

- name: set pacman mirrors
  copy:
    content: |
      Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
      Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
      Server = https://mirror.leaseweb.net/archlinux/$repo/os/$arch
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: '0644'

- name: check if mss-otg sourceme-build exists
  stat:
    path: /mss/etc/sourceme-build
  register: sourceme_build_state

- name: one-off mss-otg sourceme-build
  block:
    - name: create paths
      file:
        path: /mss/etc
        state: directory
        recurse: true

    - name: copy contents
      copy:
        content: |
            CPPFLAGS="-DNDEBUG -D_FORTIFY_SOURCE=2"
            CFLAGS="${CPPFLAGS} -g0 -s -w -pipe -O3 -march=x86-64 -mtune=generic"
            CFLAGS="${CFLAGS} -fcommon -fstack-protector-strong"
            CXXFLAGS="${CFLAGS}"
            LDFLAGS="${CFLAGS} -Wl,--as-needed,--sort-common,-z,relro,-z,now,--gc-sections,-O3"
            export CPPFLAGS CFLAGS CXXFLAGS LDFLAGS

            _NR_PROC="$(nproc)"

            MAKEFLAGS="-j${_NR_PROC} V=1"
            SAMUFLAGS="-j${_NR_PROC} -v"
            export MAKEFLAGS SAMUFLAGS

            CARCH="x86_64"
            CHOST="${CARCH}-pc-linux-gnu"
            CBUILD="${CHOST}"
            export CARCH CHOST CBUILD
        dest: /mss/etc/sourceme-build
        owner: root
        group: root
        mode: '0644'
  when: not sourceme_build_state.stat.exists
