---
- name: copy over the pacman config files
  copy:
    src: "{{ item }}"
    dest: /etc
    owner: root
    group: root
    mode: '0644'
  with_items:
    - pacman.conf
    - makepkg.conf

- name: set pacman mirrors
  copy:
    content: |
      Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
      Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch
      Server = https://mirror.leaseweb.net/archlinux/$repo/os/$arch
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: '0644'

- name: check if mss-otg sourceme-build exists
  stat:
    path: /mss/etc/sourceme-build
  register: sourceme_build_state

- name: one-off mss-otg sourceme-build
  block:
    - name: create paths
      file:
        path: /mss/etc
        state: directory
        recurse: true

    - name: download one-off sourceme-build
      get_url:
        url: 'https://raw.githubusercontent.com/gottaeat/mss-otg/master/utils/etc/sourceme-build'
        dest: /mss/etc/sourceme-build
        owner: root
        group: root
        mode: '0644'
  when: not sourceme_build_state.stat.exists
