---
- name: enable gpm
  systemd_service:
    name: gpm
    state: started
    enabled: true

- name: enable but do not start module cleanup
  systemd_service:
    name: linux-modules-cleanup
    enabled: true

- name: enable qbittorrent
  systemd_service:
    name: qbittorrent-nox@mss.service
    state: started
    enabled: true
  when: "'qbittorrent-nox' in pkgs"
