---
- name: copy over mkinitcpio related configuration
  copy:
    src: "{{ items }}"
    dest: /etc
    owner: root
    group: root
    mode: '0644'
  with_items:
    - vconsole.conf
    - mkinitcpio.conf
  notify: initramfs rebuild
