---
- name: copy over mkinitcpio.conf
  copy:
    src: mkinitcpio.conf
    dest: /etc
    owner: root
    group: root
    mode: '0644'
  notify: initramfs rebuild

- name: copy over vconsole.conf
  template:
    src: vconsole.conf.j2
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: '0644'
  notify: initramfs rebuild

- name: trigger handlers
  meta: flush_handlers
