---
- name: copy over mpd config
  copy:
    src: mpd.conf
    dest: /etc
    owner: root
    group: root
    mode: '0644'
  register: mpd_copy

- name: set mpd state
  systemd_service:
    name: mpd.service
    state: "{{ 'restarted' if mpd_copy.changed else 'started' }}"
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/1001"
  become: true
  become_user: mss
  when: not in_vm

- name: generate mpd database and runtime options
  block:
    - name: check if mpd init was done
      stat:
        path: /var/lib/mss_ansible/mpd_init
      register: mpd_init

    - name: do mpd init
      block:
        - name: call mpc
          shell:
            cmd: |
              mpc update && \
              mpc random off && \
              mpc repeat on && \
              mpc single off && \
              mpc consume off && \
              mpc crossfade 3
          become: true
          become_user: mss

        - name: set mpd_init
          file:
            path: "/var/lib/mss_ansible/mpd_init"
            state: touch
            modification_time: preserve
            access_time: preserve
      when: not mpd_init.stat.exists
  when: not in_vm
