---
- name: allow x11 to run as root
  copy:
    src: Xwrapper.config
    dest: /etc/X11
    owner: root
    group: root
    mode: '0644'

- name: copy xorg-server config for host
  copy:
    src: "xorg.conf.d/01-{{ mss_hostname }}.conf"
    dest: /etc/X11/xorg.conf.d
    owner: root
    group: root
    mode: '0644'
