---
# - - netns creation - - #
- name: copy over the lan_{{ netns_name }}_ns.service unit file
  copy:
    src: "lan_{{ netns_name }}_ns.service"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
  register: lan_ns_unit_copy

- name: daemon reload
  systemd_service:
    daemon_reload: true
  when: lan_ns_unit_copy.changed

- name: set lan_{{ netns_name }}_ns service state
  block:
    - name: enabled by default, if not in a vm
      systemd_service:
        name: "lan_{{ netns_name }}_ns.service"
        enabled: true
      when: in_vm

    - name: triggers, when on baremetal
      systemd_service:
        name: "lan_{{ netns_name }}_ns.service"
        state: "{{ 'restarted' if lan_ns_unit_copy.changed else 'started' }}"
        enabled: true
      when: not in_vm

# - - dnsmasq - - #
- name: copy over the dnsmasq configuration for {{ netns_name }}
  copy:
    src: "dnsmasq_{{ netns_name }}.conf"
    dest: /mss/etc/
    owner: root
    group: root
    mode: '0644'
  register: dnsmasq_conf_copy

- name: set dnsmasq_guest state
  block:
    - name: enabled by default, if in a vm
      systemd_service:
        name: "dnsmasq_netns@{{ netns_name }}.service"
        enabled: true
      when: in_vm

    - name: triggers, when on baremetal
      systemd_service:
        name: "dnsmasq_netns@{{ netns_name }}.service"
        state:
          "{{ \
            'restarted' if \
              dnsmasq_conf_copy.changed or \
              dnsmasq_netns_unitfile_copy.changed \
            else \
              'started' \
          }}"
        enabled: true
      when: not in_vm
