---
mss_hostname: gat
mss_fstab_extra: |
  /dev/sda1 /boot vfat defaults 0 0
mss_wireguard_ifaces:
  - lichen
main_pkgs_extra:
  - aarch64-linux-gnu-gcc
  - amd-ucode
  - arm-none-eabi-gcc
  - cdrtools
  - cmake
  - dmidecode
  - dnsmasq
  - docker
  - docker-buildx
  - docker-compose
  - efibootmgr
  - firefox
  - glfw
  - jdk-openjdk
  - lib32-libpulse
  - lib32-mangohud
  - lib32-mesa
  - lib32-vulkan-icd-loader
  - lib32-vulkan-radeon
  - libjpeg-turbo
  - libva-mesa-driver
  - libvirt
  - libvorbis
  - linux-zen-headers
  - mangohud
  - mesa-vdpau
  - obs-studio
  - openal
  - qemu-desktop
  - qt5-base
  - radeontop
  - rocm-opencl-runtime
  - sshpass
  - steam
  - virt-manager
  - vulkan-icd-loader
  - vulkan-radeon
  - wine
  - wine-mono
  - winetricks
  - xf86-video-amdgpu
user_pkgs_extra:
  - xone-dkms-git
