---
mss_hostname: ashtray
mss_fstab_extra: |
  /dev/sda1 /boot ext4 defaults 0 0
mss_wireguard_ifaces:
  - lichen
# if no extra packages are defined, a variable with no value breaks the task,
# but if just `-' is specified, that gets registered as `null', which is not a
# package. setting just `base' as it will always be present fixes this issue
# without having to spend 200 hours yaml engineering.
main_pkgs_extra:
  - base
user_pkgs_extra:
  - base
