---
mss_hostname: solitude
mss_consolefont: ter-v14n
mss_fstab_extra:

mss_wireguard_ifaces:
  - lichen
  - lichenraw

main_pkgs_extra:
  - acpid
  - efibootmgr
  - intel-ucode
  - libva-intel-driver

user_pkgs_extra:
  - thinkfan
