---
- name: copy over vim configuration
  copy:
    src: vimrc
    dest: /etc
    owner: root
    group: root
    mode: '0644'

- name: create directories
  file:
    path: "{{ item.0.0 }}/.config/vim/{{ item.1 }}"
    owner: "{{ item.0.1 }}"
    group: "{{ item.0.1 }}"
    state: directory
  loop: "{{ dir | product(subdir) | list }}"

- name: symlink vi to vim
  file:
    src: "/usr/bin/vim"
    dest: "/usr/bin/vi"
    state: link
    force: true
