---
- name: build mss-otg
  include_role:
    name: handle_meson
  vars:
    project_url: "https://github.com/gottaeat/mss-otg"
    project_name: "mss-otg"
    baremetal_path: "/mnt/mss/stuff/techy-bits/git/mss-otg"
    build_dir: "build"
    meson_args: >-
      {{
        "-Dmssdir=/mss -Dsetboxes=true" +
        (" -Dfontsize=12" if inventory_hostname == "desk1"
          else "") +
        (" -Dlandfill=true -Dst=false -Ddwm=true -Ddmenu=true"
          if "desktops" in group_names else "")
      }}

- name: setcake.py service for routers
  block:
    - name: derive wan iface name
      set_fact:
        setcake_iface: "{{ 'ppp0' if ppp_wan else 'wan' }}"

    - name: copy over unit file
      copy:
        src: setcake@.service
        dest: /etc/systemd/system
        owner: root
        group: root
        mode: '0644'
      register: setcake_unitfile_copy

    - name: daemon reload
      systemd_service:
        daemon_reload: true
      when: setcake_unitfile_copy.changed

    - name: set setcake state
      block:
        - name: enabled by default, if not in a vm
          systemd_service:
            name: "setcake@{{ setcake_iface }}.service"
            enabled: true
          when: in_vm

        - name: triggers, when on baremetal
          systemd_service:
            name: "setcake@{{ setcake_iface }}.service"
            state:
              "{{ \
                'restarted' if \
                  setcake_unitfile_copy.changed \
                else \
                  'started' \
              }}"
            enabled: true
          when: not in_vm
  when: "'routers' in group_names"
