---
- name: base named configuration
  copy:
    src: "{{ item }}"
    dest: /etc
    owner: named
    group: named
    mode: '0640'
  with_items:
    - named.conf
    - rndc.conf
  register: named_conf_copy

- name: generate /etc/rndc.key
  command:
    cmd: rndc-confgen -a -c /etc/rndc.key
    creates: /etc/rndc.key

- name: set perms for rndc.key
  file:
    path: /etc/rndc.key
    owner: root
    group: named
    mode: '0644'

- name: set named state
  block:
    - name: enabled by default
      systemd_service:
        name: named
        enabled: true

    - name: triggers
      systemd_service:
        name: named
        state: "{{ 'restarted' if named_conf_copy.changed else 'started' }}"
        enabled: true

- name: set /etc/resolv.conf
  copy:
    content: |
      search crib lichen
      nameserver 10.0.99.0
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: '0644'

- name: mask systemd-resolved
  systemd_service:
    name: systemd-resolved
    enabled: false
    masked: true
