---
- name: copy over networkmanager configuration
  copy:
    src: conf.d/
    dest: /etc/NetworkManager/conf.d/
    owner: root
    group: root
    mode: '0644'
  register: nm_config_copy

- name: set networkmanager state
  block:
    - name: enabled by default, if not in a vm
      systemd_service:
        name: NetworkManager
        enabled: true
      when: in_vm

    - name: triggers, when on baremetal
      systemd_service:
        name: NetworkManager
        state: "{{ 'reloaded' if nm_config_copy.changed else 'started' }}"
        enabled: true
      when: not in_vm
