---
- name: copy over logind config
  copy:
    src: logind.conf
    dest: /etc/systemd
    owner: root
    group: root
    mode: '0644'
  notify: restart logind

- name: enable-linger for user mss
  file:
    path: /var/lib/systemd/linger/mss
    state: touch
    modification_time: preserve
    access_time: preserve

- name: trigger handlers
  meta: flush_handlers
