---
- name: create client symlinks for {{ inventory_hostname }}
  file:
    src: "/mnt/mss/stuff/techy-bits/git/vault/genwg_dump/client/{{ inventory_hostname }}-{{ item }}.conf"
    dest: "/etc/wireguard/{{ item }}.conf"
    state: link
    force: true
    follow: false
  with_items: "{{ wireguard_ifaces }}"
  register: wg_config_link
